version: '3.8'
services:
  redis:
    image: redis:latest
    container_name: redis_server
    command: redis-server --requirepass "WBxkvwPzLOJKsxdzDxMd" --maxmemory 5mb --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"